language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

install: 'gem install bundler -v ">= 1.7.12" && bundle install --jobs=3 --retry=5'

sudo: false
