language: ruby

rvm:
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1
      jdk: openjdk7
    - rvm: 2.1
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
  fast_finish: true

branches:
  only:
    - master
