#There are six mandatory parameters: 
# site_name
# cloud_type
# endpoint
# output -> output_dir
# output -> output_type
# sidekiq -> queue
defaults: &defaults
  site_name: <fill in> #Usually a shor provider name, e.g. CESNET 
  cloud_type: OpenNebula
  endpoint: <fill in> #URL of your OCCI endpoint, e.g. https://fqdn.example.com:80
  output:
    output_dir: <fill in> #Directory for outgoing messages
    output_type: apel-0.2 #Format of outgoing messages. apel-0.2 is currently the only option.
#   num_of_vms_per_file: 500 #Maximum number of virtual machine records per one output file.
#
# logging:
#   log_type: file #Two options: file, syslog. Defaults to stdout
#   log_file: /var/log/oneacct-export.log #Used when type file selected
#
# xml_rpc:
#   secret: username:password #If not specified looking for secret in ONE_AUTH and ~/.one/one_auth.
#   endpoint: http://localhost:2633/RPC2 #Defaults to content of ONE_XMLRPC or content of ~/.one/one_endpoint or http://localhost:2633/RPC2.
#
# redis:
#   namespace: oneacct_export
#   url: redis://localhost:6379 #URL of redis server, defaults to redis://localhost:6379.
#   password: password #Password to access redis server if needed.
  sidekiq:
    queue: oneacct_export
production:
  <<: *defaults
development:
  <<: *defaults
test:
  site_name: <placeholder>
  cloud_type: <placeholder>
  endpoint: <placeholder>
  output:
    output_dir: <placeholder>  
    output_type: <placeholder>
    num_of_vms_per_file: <placeholder>
  logging:
    log_type: <placeholder>
    log_file: <placeholder>
  xml_rpc:
    secret: <placeholder>
    endpoint: <placeholder>
  redis:
    namespace: <placeholder>
    url: http://some.random.url.com
    password: password
  sidekiq:
    queue: oneacct_export
