#Five mandatory parameters: 
# site_name
# cloud_type
# endpoint
# output -> output_dir
# output -> output_type
defaults: &defaults
  site_name: <fill in> 
  cloud_type: <fill in>
  endpoint: <fill in>
  output:
    output_dir: <fill in>
    output_type: apel-0.2 #currently only option
# num_of_vms_per_file: 500
#
#logging:
# log_type: file #Two options: file, syslog. Defaults to stdout
# log_file: /var/log/oneacct-export.log #Used when type file selected
#
#xml_rpc:
# secret: username:password #If not specified looking for secret in ONE_AUTH and ~/.one/one_auth
# endpoint: http://localhost:2633/RPC2 #Defaults to content of ONE_XMLRPC or content of ~/.one/one_endpoint or http://localhost:2633/RPC2
#
#redis:
# namespace: oneacct_export
# url: redis://localhost:6379
# password: password
production:
  <<: *defaults
development:
  <<: *defaults
test:
  site_name: <placeholder>
  cloud_type: <placeholder>
  endpoint: <placeholder>
  output:
    output_dir: <placeholder>  
    output_type: <placeholder>
    num_of_vms_per_file: <placeholder>
  logging:
    log_type: <placeholder>
    log_file: <placeholder>
  xml_rpc:
    secret: <placeholder>
    endpoint: <placeholder>
  redis:
    namespace: <placeholder>
    url: http://some.random.url.com
    password: password
